local Remnants = {}

Remnants.templates = {
  {
    entities = {
      {name = "burner-mining-drill-remnants", offset = {x = -4, y = -3}},
      {name = "transport-belt-remnants", offset = {x = -4, y = 0}},
      {name = "transport-belt-remnants", offset = {x = -3, y = 0}},
      {name = "transport-belt-remnants", offset = {x = -2, y = 0}},
      {name = "burner-inserter-remnants", offset = {x = -1, y = -1}},
      {name = "stone-furnace-remnants", offset = {x = -1, y = -2}},
      {name = "wooden-chest-remnants", offset = {x = 2, y = 1}},
    },
  },
  {
    entities = {
      {name = "transport-belt-remnants", offset = {x = -3, y = 1}},
      {name = "transport-belt-remnants", offset = {x = -2, y = 1}},
      {name = "transport-belt-remnants", offset = {x = 0, y = 1}},
      {name = "burner-inserter-remnants", offset = {x = -1, y = 0}},
      {name = "burner-inserter-remnants", offset = {x = 1, y = 0}},
      {name = "stone-furnace-remnants", offset = {x = -1, y = -1}},
      {name = "stone-furnace-remnants", offset = {x = 1, y = -1}},
      {name = "wooden-chest-remnants", offset = {x = 3, y = 0}},
    },
  },
  {
    entities = {
      {name = "small-electric-pole-remnants", offset = {x = -2, y = -1}},
      {name = "small-electric-pole-remnants", offset = {x = 2, y = -1}},
      {name = "transport-belt-remnants", offset = {x = -1, y = 0}},
      {name = "transport-belt-remnants", offset = {x = 0, y = 0}},
      {name = "transport-belt-remnants", offset = {x = 1, y = 0}},
      {name = "inserter-remnants", offset = {x = 2, y = 1}},
      {name = "wooden-chest-remnants", offset = {x = 3, y = 2}},
    },
  },
  {
    entities = {
      {name = "transport-belt-remnants", offset = {x = -3, y = 1}},
      {name = "transport-belt-remnants", offset = {x = -2, y = 1}},
      {name = "inserter-remnants", offset = {x = -1, y = 1}},
      {name = "assembling-machine-1-remnants", offset = {x = 0, y = 0}},
      {name = "small-electric-pole-remnants", offset = {x = -2, y = -1}},
      {name = "wooden-chest-remnants", offset = {x = 2, y = 0}},
    },
  },
  {
    entities = {
      {name = "transport-belt-remnants", offset = {x = -4, y = 0}},
      {name = "transport-belt-remnants", offset = {x = -3, y = 0}},
      {name = "transport-belt-remnants", offset = {x = -2, y = 0}},
      {name = "inserter-remnants", offset = {x = -1, y = 0}},
      {name = "wooden-chest-remnants", offset = {x = 0, y = 0}},
      {name = "small-electric-pole-remnants", offset = {x = 2, y = -1}},
    },
  },
  {
    entities = {
      {name = "tank-remnants", offset = {x = -1, y = 0}},
      {name = "gun-turret-remnants", offset = {x = 2, y = -1}},
      {name = "wall-remnants", offset = {x = -3, y = 1}},
      {name = "wall-remnants", offset = {x = -2, y = 1}},
      {name = "wall-remnants", offset = {x = -1, y = 1}},
      {name = "small-scorchmark-tintable", offset = {x = 0, y = 1}},
      {name = "medium-scorchmark-tintable", offset = {x = 2, y = 0}},
      {name = "wooden-chest-remnants", offset = {x = 3, y = 2}},
    },
  },
  {
    entities = {
      {name = "spidertron-remnants", offset = {x = 0, y = 0}},
      {name = "behemoth-worm-corpse", offset = {x = -2, y = 2}},
      {name = "small-electric-pole-remnants", offset = {x = -3, y = -1}},
      {name = "transport-belt-remnants", offset = {x = 2, y = 2}},
      {name = "transport-belt-remnants", offset = {x = 3, y = 2}},
      {name = "small-scorchmark-tintable", offset = {x = -1, y = 1}},
      {name = "medium-scorchmark-tintable", offset = {x = 1, y = -1}},
      {name = "wooden-chest-remnants", offset = {x = 3, y = -1}},
    },
  },
  {
    entities = {
      {name = "solar-panel-remnants", offset = {x = -6, y = -3}},
      {name = "solar-panel-remnants", offset = {x = -3, y = -3}},
      {name = "solar-panel-remnants", offset = {x = 0, y = -3}},
      {name = "solar-panel-remnants", offset = {x = 3, y = -3}},
      {name = "solar-panel-remnants", offset = {x = -6, y = 0}},
      {name = "solar-panel-remnants", offset = {x = -3, y = 0}},
      {name = "solar-panel-remnants", offset = {x = 0, y = 0}},
      {name = "solar-panel-remnants", offset = {x = 3, y = 0}},
      {name = "solar-panel-remnants", offset = {x = -6, y = 3}},
      {name = "solar-panel-remnants", offset = {x = -3, y = 3}},
      {name = "solar-panel-remnants", offset = {x = 0, y = 3}},
      {name = "medium-electric-pole-remnants", offset = {x = 6, y = -2}},
      {name = "medium-electric-pole-remnants", offset = {x = 6, y = 2}},
      {name = "transport-belt-remnants", offset = {x = 1, y = 5}},
      {name = "transport-belt-remnants", offset = {x = 2, y = 5}},
    },
  },
  {
    entities = {
      {name = "straight-rail-remnants", offset = {x = 0, y = -5}},
      {name = "straight-rail-remnants", offset = {x = 0, y = -3}},
      {name = "straight-rail-remnants", offset = {x = 0, y = -1}},
      {name = "rail-signal-remnants", offset = {x = -2, y = -2}},
      {name = "train-stop-remnants", offset = {x = 2, y = -2}},
      {name = "stack-inserter-remnants", offset = {x = 2, y = 0}},
      {name = "steel-chest-remnants", offset = {x = 4, y = 1}},
      {name = "small-electric-pole-remnants", offset = {x = 3, y = -2}},
    },
  },
  {
    entities = {
      {name = "wall-remnants", offset = {x = -4, y = 0}},
      {name = "wall-remnants", offset = {x = -3, y = 0}},
      {name = "wall-remnants", offset = {x = -2, y = 0}},
      {name = "wall-remnants", offset = {x = -1, y = 0}},
      {name = "artillery-turret-remnants", offset = {x = 1, y = -1}},
      {name = "laser-turret-remnants", offset = {x = 3, y = 1}},
      {name = "big-biter-corpse", offset = {x = -5, y = 2}},
      {name = "big-biter-corpse", offset = {x = -2, y = 3}},
      {name = "big-biter-corpse", offset = {x = 2, y = 2}},
      {name = "medium-biter-corpse", offset = {x = -6, y = 1}},
      {name = "medium-biter-corpse", offset = {x = -4, y = 3}},
      {name = "medium-biter-corpse", offset = {x = -1, y = 2}},
      {name = "medium-biter-corpse", offset = {x = 1, y = 3}},
      {name = "medium-biter-corpse", offset = {x = 4, y = 2}},
      {name = "small-biter-corpse", offset = {x = -6, y = 0}},
      {name = "small-biter-corpse", offset = {x = -5, y = 1}},
      {name = "small-biter-corpse", offset = {x = -4, y = 2}},
      {name = "small-biter-corpse", offset = {x = -3, y = 3}},
      {name = "small-biter-corpse", offset = {x = -1, y = 1}},
      {name = "small-biter-corpse", offset = {x = 0, y = 2}},
      {name = "small-biter-corpse", offset = {x = 1, y = 2}},
      {name = "small-biter-corpse", offset = {x = 2, y = 3}},
      {name = "small-biter-corpse", offset = {x = 3, y = 2}},
      {name = "small-biter-corpse", offset = {x = 5, y = 1}},
      {name = "medium-scorchmark-tintable", offset = {x = 0, y = 2}},
      {name = "medium-electric-pole-remnants", offset = {x = 4, y = -2}},
    },
  },
  {
    entities = {
      {name = "pipe-remnants", offset = {x = -4, y = 0}},
      {name = "pipe-remnants", offset = {x = -3, y = 0}},
      {name = "pipe-remnants", offset = {x = -2, y = 0}},
      {name = "pipe-remnants", offset = {x = -1, y = 0}},
      {name = "pipe-remnants", offset = {x = 0, y = 0}},
      {name = "pipe-remnants", offset = {x = 1, y = 0}},
      {name = "pump-remnants", offset = {x = 3, y = 0}},
      {name = "storage-tank-remnants", offset = {x = 5, y = 1}},
    },
  },
  {
    entities = {
      {name = "straight-rail-remnants", offset = {x = 0, y = -4}},
      {name = "straight-rail-remnants", offset = {x = 0, y = -2}},
      {name = "straight-rail-remnants", offset = {x = 0, y = 0}},
      {name = "stack-inserter-remnants", offset = {x = 1, y = 1}},
      {name = "stack-inserter-remnants", offset = {x = 1, y = 2}},
      {name = "transport-belt-remnants", offset = {x = 2, y = 3}},
      {name = "transport-belt-remnants", offset = {x = 2, y = 4}},
      {name = "steel-chest-remnants", offset = {x = 1, y = 5}},
    },
  },
}

Remnants.guaranteed = {
  {origin = {x = -84, y = -12}, template_index = 1},
  {origin = {x = 90, y = 26}, template_index = 2},
  {origin = {x = -18, y = 88}, template_index = 4},
  {origin = {x = 76, y = -78}, template_index = 3},
  {origin = {x = -92, y = 64}, template_index = 5},
  {origin = {x = 28, y = 108}, template_index = 6},
  {origin = {x = 118, y = -8}, template_index = 8},
  {origin = {x = -126, y = 20}, template_index = 9},
  {origin = {x = 66, y = 126}, template_index = 10},
  {origin = {x = -54, y = -118}, template_index = 11},
  {origin = {x = 122, y = 84}, template_index = 12},
}

return Remnants
